version: '3'
services:
  nuxt:
    build: .
    environment:
      - "HTTP_ENDPOINT=http://localhost:8001/graphql"
      - "APP_URL=http://localhost:8001"
    tty: true
    volumes:
      - ".:/Twimon"
    ports:
      - "3000:3000"