query GetLikeUsers ($perPage:Int!,$page:Int!,$name:String,$searchTypes:[String],$withDescription:Boolean,$talkEditedFlg:Boolean){
  getLikeUsers(perPage: $perPage, page:$page,name:$name,searchTypes: $searchTypes,withDescription: $withDescription,talkEditedFlg: $talkEditedFlg){
    likeUsers{
          id
          serial_number
          name
          type1
          type2
          feature1
          feature1_content
          feature2
          feature2_content
          description1
          description2
          description3
          sns_img_url
          ogp_img_url
          hall_of_fame_flg
          legend_flg
          like_ct
          liked
    }
    paginatorInfo{
      currentPage
      lastPage
    }
    
  }
}
