query getLikeUsers($like_user_id:ID!){
  getLikeUsers(count: 20, page: 1,liked_user_id:$like_user_id){
    data {
      id
      liked_user_id
      user{
          id
          serial_number
          name
          feature1
          feature1_content
          feature2
          feature2_content
          description
          sns_img_url
          ogp_img_url
          hall_of_fame_flg
          legend_flg
          like_ct
          liked
      }
    }
    paginatorInfo {
        currentPage
        lastPage
    }
  }
}