{
  me{
    id
    serial_number
    name
    title
    feature1
    feature1_content
    feature2
    feature2_content
    description
    sns_img_src
    hall_of_fame_flg
    legend_flg
    like_ct
  }
}