{
  me{
    id
    serial_number
    name
    title
    feature1
    feature1_content
    feature2
    feature2_content
    description
    upload_img_url
    sns_img_url
    sns_img_use_flg
    ogp_img_url
    hall_of_fame_flg
    legend_flg
    like_ct
  }
}