query GetUsers ($page:Int!){
    users(count: 12, page: $page) {
        data {
            id
            name
            feature1
            feature1_content
            feature2
            feature2_content
            description
          	img_src
        }
        paginatorInfo {
            currentPage
            lastPage
        }
    }
}