query GetUsers ($page:Int!){
    users(count: 12, page: $page,orderBy: [
            {
                field: "id"
                order: ASC
            }
        ]) {
        data {
            id
            serial_number
            name
            type1
            type2
            feature1
            feature1_content
            feature2
            feature2_content
            description1
            description2
            description3
            sns_img_url
            ogp_img_url
            hall_of_fame_flg
            legend_flg
          	like_ct
          	liked
        }
        paginatorInfo {
            currentPage
            lastPage
        }
    }
}